---
title: 'DATA 607: Scenario Design for Spotify''s AI DJ'
author: "Kevin Kirby"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 11 discussion overview

Week 11 discussion hasn 4 component questions that I will use Spotify's AI DJ product to answer:

* Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.
* Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
* Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
* Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.

## Scenario Design Analysis

There are three component questions to a Scenario Design Analysis:

* Who are your target users?
* What are their key goals?
* How can you help them accomplish their goals?

### Who are your target users?

The target users and passionate music fans who are looking for an automated way to discover new music. Music discovery remains a largely tire fire experience for most users, with a lot of reccomendation systems simply suggesting whatever son you've been listening to recently. These users exist across a wide spectrum of music tastes and each need new music that fits their identity profile or identity cluster.

### What are their key goals?

The key goals of this segment is of music listeners is to find new musc that they would not have otherwise found while still being on their current sound landscape. The goal is to push the boundaries of what they understand as good music whole not going totally off the rails by being given a techno song when they've been listening to classical jazz. They want to take their music tastes in new and unexpected directions but do so through refined incrementalism instead of shock and awe.

### How can you help them accomplish their goals?

Current music recommendation systems index heavily towards what you've been listening to rather than where music trends are going for people like you. Spotify AI DJ seeks to address this by incorporating elements of what you've been listening to on a longer look back arch with elements of what others are listening to as well. It incorporates a drive time radio DJ element by having a catty (bordering on obnoxious) AI robot respond to your feedback and try and adapt on the fly. 

## Reverse engineer Spotify AI DJ

The product leans heavily on Spotify's existing Playlist infrastructure as the technical backbone of the product. They key difference is that you can't toggle into the playlist itself and see what's coming up next, the premise being that the playlist is being made on the fly by the AI DJ. The AI personality does annoyingly to you a lot, similar to how drive time radio DJs chatter in between songs. As with any song, you can like it and add it to your Liked Songs playlist or click three dots and add it to any other playlist you have. The blue hue used does break from Spotify's traditional dark green color tones, which is both fun and kind of bizarre. 

## How to improve the product

1. Reduce the amount of talking from the AI DJ, or create an option to reduce the amount of talking. People want new music, not another corporate chatbot overlord
2. Incorporate elements from Spotify's Tunnel Vision playlist, where house ansd techno songs play nonstop and it feels smoother because it skips the first 30 seconds of the next song (often the "intro" of a song that's used for transitions)
3. Create more sophisticated feedback mechanisms through large language modeling. ChatGPT, for example, has ways for users to directly insert their preferences for questions and answers. Spotify's AI DJ should have somethins similar so users can write what they're looking for in natural language.



